### ISSUE TITLE
Font in address bar changes to unreadable size

### ISSUE THREAD

**Issue by Henttu** [lstratman/EasyConnect#79] opened 2018-05-08 10:21 UTC
After updating to latest version (2.1.0.0), the font in address bar goes way up when it's not active.

![image](https://user-images.githubusercontent.com/31536557/39751788-f9697ef2-52c1-11e8-9b9d-5531ba5b1d57.png)

**Comment by lstratman** [comment] 2018-05-08 19:01
Interesting, can't say that I've seen that before :).  Do you have text scaling enabled for your display by any chance?

![image](https://user-images.githubusercontent.com/24588/39777112-b168e1b0-52d0-11e8-9f59-73f76af73e69.png)

**Comment by Henttu** [comment] 2018-05-09 06:40
Well, yes and no. We use company wide script that forces 100% scale, because Microsoft. This is what it looks like in display settings:
![image](https://user-images.githubusercontent.com/31536557/39799144-d923d08e-536b-11e8-9fb8-afd83bd8724f.png)
Clicking Custom scaling shows that it's actually 100%. This is on 1709 version of Win10, my co-worker has the same problem with his. This did not happen on an earlier version of EasyConnect on same machine, though. I think it was 1.5.1, maybe...?

**Comment by lstratman** [comment] 2018-05-09 15:45
I've changed the assembly that I use for HTML rendering for the URL bar and the omnibox to a newer, less dodgy NuGet package that should hopefully fix this issue.  You can install the CI build from https://ci.appveyor.com/api/projects/lstratman/EasyConnect/artifacts/Installer/bin/Release/EasyConnect.msi; let me know if that works for you and I'll publish an official build.

**Comment by Henttu** [comment] 2018-05-11 07:31
Unfortunately, it's still the same:
![image](https://user-images.githubusercontent.com/31536557/39912112-4946e9fa-5506-11e8-9e67-5d953edbce21.png)
Version is now 2.1.2.55

**Comment by cpetit-sigma-fr** [comment] 2018-12-17 17:36
Same here. My 3 screens (laptop, 24" #1 and 24" #2) are all scaled at 100%. Windows 10 1803.

**Comment by mstrini** [comment] 2019-04-26 08:09
the problem ist that the font size for rendering is convertert from a float-value (urlTextBox.Font.SizeInPoints) to string using the current culture settings. 
That means e.g. in Germany you get `"font-size: 11,25pt"` (with comma instead of period) which will be interpreted by the html-renderer the wrong way.

So the conversion to string should be done with `System.Globalization.CultureInfo.InvariantCulture` e.g.
`string.Format(System.Globalization.CultureInfo.InvariantCulture, "font-size: {0}pt, urlTextBox.Font.SizeInPoints)`

**Closed** 2020-10-05 15:01 UTC

**Comment by mstrini** [comment] 2020-10-08 09:27
Hi,
when is the next release scheduled? 
Would be nice to use the fixed version via windows app store...

5. Oktober 2020 17:02, "Luke Stratman" <notifications@github.com (mailto:notifications@github.com?to=%22Luke%20Stratman%22%20<notifications@github.com>)> schrieb:
	Closed #79 (https://github.com/lstratman/EasyConnect/issues/79) via 5667ed7 (https://github.com/lstratman/EasyConnect/commit/5667ed7f1c3f71bb6f7f31d26660ea27d07e9161).
